/*
 * This source file was generated by the Gradle 'init' task
 */
package comp3310a1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertTrue(true); // no tests to pass
    }
}
